#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import subprocess
import datetime as dt
from flask.ext.script import Manager, Shell, Server
from flask.ext.migrate import MigrateCommand

from DictionaryOfNewZealandEnglish.app import create_app
from DictionaryOfNewZealandEnglish.user.models import User, Flag, Homonym_number, Word_class, Sense_number, Register, Domain, Region, Origin, Source, Data_set
from DictionaryOfNewZealandEnglish.settings import DevConfig, ProdConfig
from DictionaryOfNewZealandEnglish.database import db

if os.environ.get("DICTIONARYOFNEWZEALANDENGLISH_ENV") == 'prod':
    app = create_app(ProdConfig)
else:
    app = create_app(DevConfig)

HERE = os.path.abspath(os.path.dirname(__file__))
TEST_PATH = os.path.join(HERE, 'tests')

manager = Manager(app)

def _make_context():
    """Return context dict for a shell session so you can access
    app, db, and the User model by default.
    """
    return {'app': app, 'db': db, 'User': User}

@manager.command
def test():
    """Run the tests."""
    import pytest
    exit_code = pytest.main([TEST_PATH, '--verbose'])
    return exit_code


@manager.command
def seed():    
    User.create( username="admin", 
                 email="admin@example.com", 
                 institution="NZDC VUW",
                 country="NZ",
                 interest="Admin role",
                 password="password", 
                 updated_at=dt.datetime(2015, 3, 8, 7, 36, 19, 347404), 
                 active=True )
    User.create( username="Matt", 
                 email="matt@example.com", 
                 institution="NZDC VUW",
                 country="NZ",
                 interest="Admin role",
                 password="password", 
                 updated_at=dt.datetime(2015, 3, 8, 7, 36, 19, 347404), 
                 active=True )

    Flag.create( id=1,
                 name="Transport",
                 notes="DB",
                 archived=False,
                 updated_at=dt.datetime(2004, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Flag.create( id=2,
                 name="Slang",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 1, 13, 0, 0, 0, 0),
                 updated_by="")
    Flag.create( id=3,
                 name="Farm Words",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 12, 16, 0, 0, 0, 0),
                 updated_by="rscholes")
    Flag.create( id=4,
                 name="Geology",
                 notes="Geology",
                 archived=False,
                 updated_at=dt.datetime(2012, 10, 17, 0, 0, 0, 0),
                 updated_by="jan")

    Homonym_number.create( id=11,
                 name="1",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=18,
                 name="2",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=19,
                 name="3",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=20,
                 name="4",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=22,
                 name="5",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=23,
                 name="6",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=24,
                 name="7",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=25,
                 name="8",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Homonym_number.create( id=26,
                 name="9",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")

    Word_class.create( id=69,
                 name="[none]",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 8, 20, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=39,
                 name="abbreviation",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 8, 1, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=12,
                 name="adjective",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(1999, 8, 6, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=17,
                 name="adverb",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(1999, 8, 24, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=27,
                 name="conjunction",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2000, 9, 8, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=71,
                 name="determiner",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2006, 5, 20, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=23,
                 name="exclamation",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(1999, 10, 12, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=1,
                 name="noun",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(1999, 8, 17, 0, 0, 0, 0),
                 updated_by="dhurley")
    Word_class.create( id=9,
                 name="phrase",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(1999, 7, 26, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=73,
                 name="prefix",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2010, 2, 12, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=30,
                 name="preposition",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2000, 11, 16, 0, 0, 0, 0),
                 updated_by="")
    Word_class.create( id=8,
                 name="pronoun",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(1999, 7, 26, 0, 0, 0, 0),
                 updated_by="dhurley")
    Word_class.create( id=13,
                 name="verb",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(1999, 8, 9, 0, 0, 0, 0),
                 updated_by="")

    Sense_number.create( id=2,
                 name="1",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=25,
                 name="2",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=37,
                 name="3",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=48,
                 name="4",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=59,
                 name="5",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=70,
                 name="6",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=80,
                 name="7",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=91,
                 name="8",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Sense_number.create( id=101,
                 name="9",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")

    Register.create( id=1,
                 name="[none]",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=19,
                 name="archaic",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2006, 2, 10, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=16,
                 name="corse slang",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Register.create( id=9,
                 name="dated",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=11,
                 name="derogatory",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=15,
                 name="ephemistic",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=4,
                 name="formal",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 20, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=6,
                 name="historical",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 20, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=14,
                 name="humorous",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=5,
                 name="informal",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Register.create( id=12,
                 name="literary",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=20,
                 name="obsolete",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2007, 4, 26, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=7,
                 name="offensive",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 20, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=13,
                 name="rare",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Register.create( id=17,
                 name="trademark",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")

    Domain.create( id=1,
                 name="[none]",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2002, 1, 1, 0, 0, 0, 0),
                 updated_by="")
    Domain.create( id=16,
                 name="Commerce",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Domain.create( id=4,
                 name="Cuisine",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Domain.create( id=8,
                 name="Environment",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Domain.create( id=5,
                 name="Geology",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Domain.create( id=12,
                 name="Marine",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Domain.create( id=20,
                 name="Media",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Domain.create( id=27,
                 name="Politics",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2006, 2, 10, 0, 0, 0, 0),
                 updated_by="")
    Domain.create( id=3,
                 name="Rural",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Domain.create( id=26,
                 name="Science",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2006, 2, 10, 0, 0, 0, 0),
                 updated_by="")
    Domain.create( id=6,
                 name="Sport",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="dbardsl")

    Region.create( id=1,
                 name="[none]",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Region.create( id=3,
                 name="New Zealand and Australia",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 20, 0, 0, 0, 0),
                 updated_by="")
    Region.create( id=7,
                 name="New Zealand (Southern South Island)",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 27, 0, 0, 0, 0),
                 updated_by="")
    Region.create( id=8,
                 name="New Zealand (Weat Coast South Island)",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 27, 0, 0, 0, 0),
                 updated_by="")
    Region.create( id=9,
                 name="New Zealand and Pacific",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2006, 2, 10, 0, 0, 0, 0),
                 updated_by="")


    Origin.create( id=2,
                 name="[none]",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 10, 20, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=18,
                 name="abbreviation",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2006, 10, 26, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=10,
                 name="Aboriginal",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=8,
                 name="acronym",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=19,
                 name="blend",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2007, 1, 15, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=11,
                 name="British dialect",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=12,
                 name="catchphrase",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=17,
                 name="ellipsis",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=22,
                 name="eponym",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2007, 8, 9, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=15,
                 name="euphemism",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=16,
                 name="expletive",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=14,
                 name="initialism",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=4,
                 name="Maori",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=21,
                 name="Moriori",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2007, 6, 22, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=7,
                 name="Polynesian",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="dbardsl")
    Origin.create( id=9,
                 name="rhyming slang",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=5,
                 name="Samoan",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=6,
                 name="Tongan",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2005, 11, 29, 0, 0, 0, 0),
                 updated_by="")
    Origin.create( id=23,
                 name="toponym",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2007, 8, 9, 0, 0, 0, 0),
                 updated_by="")

    Data_set.create( id=1,
                 name="Orsman",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2015, 3, 9, 0, 0, 0, 0),
                 updated_by="Matt")
    Data_set.create( id=2,
                 name="DNZE",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2015, 3, 9, 0, 0, 0, 0),
                 updated_by="")
    Data_set.create( id=3,
                 name="Incomings",
                 notes="",
                 archived=False,
                 updated_at=dt.datetime(2015, 3, 9, 0, 0, 0, 0),
                 updated_by="")




manager.add_command('server', Server())
manager.add_command('shell', Shell(make_context=_make_context))
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
