"""empty message

Revision ID: 1c1b7271ef6c
Revises: 241caef0aa3
Create Date: 2015-02-22 22:03:40.073884

"""

# revision identifiers, used by Alembic.
revision = '1c1b7271ef6c'
down_revision = '241caef0aa3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    ### end Alembic commands ###
